import React from "react";
import "../assets/styles/CategoryDropdown.scss";
import { useState } from "react";
import kadin_icon from "../assets/images/kadin_icon.png";
import erkek_icon from "../assets/images/erkek_icon.png";
import anne_cocuk from "../assets/images/anne_cocuk.png";
import ev_mobilya from "../assets/images/ev_mobilya.png";
import market from "../assets/images/market.png";
import kozmetik from "../assets/images/kozmetik.png";
import ayakkabi_canta from "../assets/images/kozmetik.png";
import elektronik from "../assets/images/elektronik.png";
import spor_outdoor from "../assets/images/spor_outdoor.png";
import kirtasiye from "../assets/images/kirtasiye.png";
import right_icon from "../assets/images/right_icon.png";

const data = [
  {
    name: "Kadın",
    icon: kadin_icon,
    subcategories: [
      {
        name: "Giyim",
        items: [
          "Elbise",
          "Tişört",
          "Gömlek",
          "Kot Pantolon",
          "Kot Ceket",
          "Pantolon",
          "Mont",
          "Bluz",
          "Ceket",
          "Etek",
          "Kazak",
          "Tesettür",
          "Büyük Beden",
          "Trençkot",
          "Yağmurluk & Rüzgarlık",
          "Sweatshirt",
          "Kaban",
          "Hırka",
          "Palto",
        ],
      },
      {
        name: "Ayakkabı",
        items: [
          "Topuklu Ayakkabı",
          "Sneaker",
          "Günlük Ayakkabı",
          "Babet",
          "Sandalet",
          "Bot",
          "Çizme",
          "Kar Botu",
          "Loafer",
        ],
      },
      {
        name: "Aksesuar & Çanta",
        items: [
          "Çanta",
          "Saat",
          "Takı",
          "Cüzdan",
          "Atkı",
          "Bere",
          "Eldiven",
          "Kemer",
          "Şal",
        ],
      },
      {
        name: "Çanta",
        items: [
          "Omuz Çantası",
          "Sırt Çantası",
          "Bel Çantası",
          "Okul Çantası",
          "Laptop",
          "Portföy",
          "Postacı Çantası",
          "El Çantası",
          "Kanvas Çanta",
          "Makyaj Çantası",
          "Abiye Çanta",
          "Çapraz Çanta",
          "Bez Çanta",
          "Anne Bebek Çantası",
          "Evrak Çantası",
          "Tote Çanta",
          "Beslenme Çantası",
          "Kartlık",
          "Cüzdan",
          "Kadın Spor Çantası",
        ],
      },
      {
        name: "İç Giyim",
        items: [
          "Pijama",
          "Gecelik",
          "Sütyen",
          "İç Çamaşırı Takımları",
          "Çorap",
          "Korse",
          "Külot",
          "Büstiyer",
          "Bralet",
          "Atlet & Body",
          "Kombinezon",
          "Jartiyer",
        ],
      },
      {
        name: "Kozmetik",
        items: [
          "Parfüm",
          "Göz Makyajı",
          "Cilt Bakımı",
          "Saç Bakımı",
          "Makyaj",
          "Ağız Bakım",
          "Cinsel Sağlık",
          "vücut Bakım",
          "Hijyenik Ped",
          "Duş Jeli & Kremleri",
          "Epilasyon Ürünleri",
          "Ruj",
          "Dudak Nemlendirici",
          "Aydınlatıcı & Highlighter",
          "Eyeliner",
          "Ten Makyajı",
          "Manikür & Pedikür",
          "BB & CC Krem",
          "El Kremi",
          "Yüz Nemlendirici",
        ],
      },
      {
        name: "Spor & Outdoor",
        items: [
          "Sweatshit",
          "Tişört",
          "Spor Sütyeni",
          "Tayt",
          "Eşofman",
          "Koşu Ayakkabısı",
          "Spor Çantası",
          "Spor Ekipmanları",
          "Outdoor Ekipmanları",
          "Sporcu Besinleri",
          "Sporcu Aksesuarları",
          "Outdoor Çanta",
          "Kayak Malzemeleri",
          "Uyku Tulumu",
          "Mat",
          "Dağcılık",
          "Kadın Spor Ceket",
          "Spor Ayakkabı",
        ],
      },
    ],
  },

  {
    name: "Erkek",
    icon: erkek_icon,
    subcategories: [
      {
        name: "Giyim",
        items: [
          "Tişört",
          "Şort",
          "Gömlek",
          "Eşofman",
          "Pantolon",
          "Ceket",
          "Kot Pantolon",
          "Yelek",
          "Kazak",
          "Mont",
          "Takım Elbise",
          "Sweatshirt",
          "Deri Mont",
          "Kaban",
          "Hırka",
          "Trençkot",
          "Palto",
          "Yağmurluk",
          "Blazer",
          "Polar",
        ],
      },
      {
        name: "Ayakkabı",
        items: [
          "Spor Ayakkabı",
          "Günlük Ayakkabı",
          "Yürüyüş Ayakkabısı",
          "Krampon",
          "Sneaker",
          "Klasik",
          "Bot",
          "Kar Botu",
          "Deri ayakkabı",
          "Loafer",
          "Ev Terliği",
          "Koşu Ayakkabısı",
          "Çizme",
        ],
      },
      {
        name: "Kişisel Bakım",
        items: [
          "Parfüm",
          "Cinsel Sağlık",
          "Tıraş Sonrası Ürünler",
          "Tıraş Bıçağı",
          "Deodorant",
        ],
      },
      {
        name: "Çanta",
        items: [
          "Sırt Çantası",
          "Spor Çanta",
          "Laptop Çantası",
          "Valiz & Bavul",
          "Postacı Çantası",
          "Bez Çanta",
          "Evrak Çantası",
          "Cüzdan",
        ],
      },
      {
        name: "Büyük Beden",
        items: [
          "Büyük Beden Sweatshirt",
          "Büyük Beden T-shirt",
          "Büyük Beden Gömlek",
          "Büyük Beden Pantolon",
          "Büyük Beden Mont",
          "Büyük Beden Kazak",
          "Büyük Beden Hırka",
          "Büyük Beden Kaban",
        ],
      },
      {
        name: "Saat & Aksesuar",
        items: [
          "Saat",
          "Güneş Gözlüğü",
          "Cüzdan",
          "Kemer",
          "Çanta",
          "Şapka",
          "Kartlık",
          "Valiz",
          "Kravat",
          "Boyunluk",
          "Atkı",
          "Bere",
          "Eldiven",
        ],
      },
      {
        name: "İç Giyim",
        items: ["Boxer", "Çorap", "Pijama", "Atlet", "İçlik"],
      },
      {
        name: "Spor & Outdoor",
        items: [
          "Eşofman",
          "Spor Ayakkabı",
          "T-shirt",
          "Sweatshirt",
          "Forma",
          "Spor Çorap",
          "Spor Giyim",
          "Outdoor Ayakkabı",
          "Outdoor Bot",
          "Spor Ekipmanları",
          "Outdoor Ekipmanları",
          "Sporcu Besinleri",
          "Sporcu Aksesuarları",
          "Sneaker",
          "Scooter",
          "Bisiklet",
          "Dalış Malzemeleri",
          "Rüzgarlık",
          "Aksiyon Kamerası",
          "Kamp Malzemeleri",
        ],
      },
      {
        name: "Elektronik",
        items: [
          "Tıraş Makinesi",
          "Cep Telefonu",
          "Akıllı Saat",
          "Akıllı Bileklik",
          "Laptop",
          "Oyun & Konsollar",
          "Elektrikli Bisiklet",
          "E-pin ve Cüzdan Kodu",
          "Playstation 5",
          "Hediye Kartları",
          "Bluetooth Kulaklık",
          "Gaming PC",
          "Oyuncu Koltuğu",
          "Xbox Series X",
          "Drone",
        ],
      },
    ],
  },

  {
    name: "Anne & Çocuk",
    icon: anne_cocuk,
    subcategories: [
      {
        name: "Bebek",
        items: [
          "Bebek Takımları",
          "Ayakkabı",
          "Hastane Çıkışı",
          "Yenidoğan Kıyafetleri",
          "Tulum",
          "Body & Zıbın",
          "Tişört & Atlet",
          "Elbise",
          "Şort",
          "Bebek Patiği",
          "Hırka",
          "Battaniye",
          "Alt Üst Takım",
          "Tişört",
          "Etek",
          "Çorap",
          "Şapka",
          "Eldiven",
          "Eşofman",
          "Bere",
        ],
      },
      {
        name: "Kız Çocuk",
        items: [
          "Elbise",
          "Sweatshirt",
          "Spor Ayakkabı",
          "Eşofman",
          "İç Giyim & Pijama",
          "Tişört & Atlet",
          "Tayt",
          "Günlük Ayakkabı",
          "Şort",
          "Mont",
          "Çocuk Oyun Evi",
          "Oyuncak Bebek",
          "Oyuncak Mutfak",
          "Kaban",
          "Abiye & Elbise",
          "Ceket",
          "Pantolon",
          "Kazak",
          "Bot",
          "Şapka & Bere & Eldiven",
        ],
      },
      {
        name: "Erkek Çocuk",
        items: [
          "Sweatshirt",
          "Spor Ayakkabı",
          "Eşofman",
          "İç Giyim & Pijama",
          "Tişört & Atlet",
          "Günlük Ayakkabı",
          "Okul Çantası",
          "Şort",
          "Gömlek",
          "Mont",
          "Oyuncak Traktör",
          "Akülü Araba",
          "Kumandalı Araba",
          "Bisiklet",
          "Boxer",
          "İçlik",
          "Bot",
          "Krampon",
          "Şapka & Bere & Eldiven",
          "Takım Elbise",
        ],
      },
      {
        name: "Bebek Takımı",
        items: [
          "Bebek Bezi",
          "Bebek Şampuanı",
          "Krem & Yağlar",
          "Bebek Çantası",
          "Bebek Sabunları",
          "Bebek Deterjanları",
          "Bebek Vücut Kremi",
          "Islak Mendil",
          "Bebek Tarağı",
          "Bebek Yağı",
          "Bebek Buhar Makinesi",
          "Bebek Ateş Ölçer",
        ],
      },
      {
        name: "Oyuncak",
        items: [
          "Eğitici Oyuncaklar",
          "Oyuncak Araba",
          "Oyuncak Bebek",
          "Bebek & Okul Öncesi",
          "Kumandalı Oyuncak",
          "Robot Oyuncak",
          "Çocuk Çizim Tableti",
        ],
      },
      {
        name: "Beslenme Emzirme",
        items: [
          "Biberon & Emzik",
          "Göğüs Pompası",
          "Mama Sandalyesi",
          "Mama Önlüğü",
          "Alıştırma Bardağı",
          "Biberon Temizleyici",
          "Biberon Seti",
          "Bebek Maması",
          "Kavanoz Mama",
          "Sterilizatör",
          "Bebek Bakım Çantası",
          "Yemek Setleri",
          "Kaşık Maması",
          "Buharlı Pişirici",
          "Termal Çanta",
          "Süt Pompası",
          "Emzirme Önlüğü",
          "Emzirme Minderi",
          "Göğüs Pedi",
          "Göğüs Kremi",
        ],
      },
    ],
  },

  {
    name: "Ev & Mobilya",
    icon: ev_mobilya,
    subcategories: [
      {
        name: "Sofra & Mutfak",
        items: [
          "Tencere & Tencere Seti",
          "Tava",
          "Düdüklü Tencere",
          "Yemek Takımnı",
          "Kahvaltı Takımı",
          "Tabak",
          "Çatal Kaşık Bıçak Seti",
          "Sakalama Kabı",
          "Bardak",
          "Kahve Fincanı",
        ],
      },
      {
        name: "Ev Gereçleri",
        items: [
          "Hurç",
          "Düzenleyiciler",
          "Askı",
          "Çamaşır Sepeti",
          "Banyo Düzenleyici",
          "Banyo Setleri",
          "Ütü Masası ve Aksesuarları",
          "Makyaj & Takı Organizeri",
        ],
      },
      {
        name: "Ev Tekstili",
        items: [
          "Nevresim & Pike Takımı",
          "Yastık & Yorgan",
          "Çarşaf & Alez",
          "Yatak Örtüsü & Battaniye",
          "Uyku Seti",
          "Koltuk Örtüsü",
          "Havlu & Bornoz",
          "Banyo Paspası",
          "Halı & Kilim",
          "Perde",
          "Seccade",
        ],
      },
      {
        name: "Ev Dekorasyon",
        items: [
          "Ayna",
          "Tablo",
          "Dekoratif Çiçek & Vazo",
          "Kırlent & Kırlent Kılıfı",
          "Duvar Saati",
          "Oda Kokusu & Mum",
          "Trendyol Sanat",
        ],
      },
      {
        name: "Aydınlatma",
        items: ["Avize", "Lambader", "Masa ve Gece Lambası"],
      },
      {
        name: "Mobilya",
        items: [
          "Salon & Oturma Odası",
          "Yatak Odası",
          "Bahçe Mobilyası",
          "Çalışma Odası",
          "Yemek Odası",
          "Oturma Grupları",
          "Genç Odası",
          "Koltuk Takımı",
          "Mutfak Tezgahı",
          "Dolap",
          "Gardırop",
          "Sandalye",
          "Zigon",
        ],
      },
      {
        name: "Hobi",
        items: [
          "Parti Malzemeleri",
          "Müzik Alet ve Ekipmanları",
          "Hediyelik Ürünler",
          "Hobi Malzemeleri",
          "Uzaktan Kumandalı Araba",
          "Drone",
          "Oyun Grupları",
          "Hediye Sepeti",
          "Led Işık",
        ],
      },
      {
        name: "Spor & Outdoor",
        items: [
          "Koşu Bandı",
          "Dumbell & Ağırlık",
          "Pilates & Yoga",
          "Eliptik Bisiklet",
          "Yoga Matı",
          "Sporcu Eldiveni",
          "Pilates Topu",
          "Sporcu Sulukları",
          "Termoslar",
        ],
      },
      {
        name: "Kitap",
        items: [
          "Sınav Hazırlık Kitapları",
          "Ders ve Yardımcı Kitaplar",
          "Roman & Edebiyat Kitapları",
          "Kişisel Gelişim & Psikoloji",
          "Çocuk Bakım Kitapları",
          "Yabancı Dil Eğitim Kitapları",
          "E-Kitaplar",
          "Din Kitapları",
          "Çizgi Roman ve Manga",
          "Yabancı Dil Çocuk Kitapları",
        ],
      },
      {
        name: "Kırtasiye",
        items: [
          "Defter",
          "Ajanda",
          "Fotokopi Kağıdı",
          "Kalem",
          "Boya Seti",
          "Dosyalama Arşivleme",
          "Masaüstü Gereçleri",
          "Ofis Teknolojisi",
        ],
      },
      {
        name: "Otomobil & Motosiklet",
        items: [
          "Oto Aksesuar",
          "Oto Paspası",
          "Oto Lastik",
          "Kask",
          "Kol Dayama & Kolçak",
          "Güneşlik & Perde",
          "Araç Kokusu",
          "Motosiklet Eldiveni",
          "Motosiklet Montu",
          "Motosiklet Botu",
          "Motosiklet Sepeti",
        ],
      },
      {
        name: "Yapı Market",
        items: [
          "Banyo Yapı Malzemeleri",
          "Elektrikli Ev Aleti",
          "Hırdavat Ürünleri",
          "Boya",
          "Matkap",
          "Ampul",
          "Vidalama",
        ],
      },
    ],
  },
  {
    name: "Süpermarket",
    icon: market,
    subcategories: [
      {
        name: "Ev & Temzilik",
        items: [
          "Çamaşır Yıkama",
          "Bulaşık Yıkama",
          "Paspas & Mop",
          "Çamaşır Deterjanı",
          "Bulaşık Deterjanı",
          "Oda Korkusu",
          "Banyo Temizleyiciler",
          "Yumuşatıcı",
          "Islak Mendil",
          "Tuvalet Kağıdı",
          "Kağıt Havlu",
          "Temizlik Bezi",
        ],
      },
      {
        name: "Kişisel Bakım",
        items: [
          "Saç Bakım",
          "Ağda & Epilasyon",
          "Banyo & Duş",
          "Ağız Bakım",
          "Cilt Bakım",
          "Vücut Bakım",
          "Deodorant ve Roll on",
          "Şarjlı Diş Fırçaları",
          "Kadın Hijyen",
          "Kolonya",
          "Tıraş Ürünleri",
          "Güneş Ürünleri",
        ],
      },
      {
        name: "Bebek Bakımı",
        items: [
          "Süt Arttırıcı İçecekler",
          "Bebek Ek Besin",
          "Bebek Bezi",
          "Islak Mendil & Havlu",
          "Bebek Kozmetik",
          "Bebek Burun Aspiratörü",
          "Bebek Diş Fırçası",
          "Bebek Mamaları",
          "Bebek Diş Macunu",
          "Bebek Temizleme Pamuğu",
          "Bebek Güneş Kremi",
          "Bebek Pudrası",
          "Bebek Tırnak Makası",
          "Bebek Pişik Kremi",
          "Bebek Yağı",
          "Bebek Bakım Seti",
          "Bebek Şampuanı",
          "Bebek Kolonyası",
          "Bebek Bakım Örtüsü",
          "Bebek Ateş Ölçer",
        ],
      },
      {
        name: "Gıda ve İçecek",
        items: [
          "Çay",
          "Özel Gıda",
          "Atıştırmalık",
          "Kahvaltılık",
          "Kuru Gıda",
          "Kahve",
          "Makarna",
          "Salça",
          "Sıvı Yağ",
          "Un",
          "Tuz & Baharat",
          "Çorba",
          "Gevrek",
          "Yulaf",
          "Konserve",
          "Şeker",
          "Süt",
          "Pasta Süslemeleri",
          "Bitki Çayları",
          "Gazsız İçecekler",
        ],
      },
      {
        name: "Atıştırmalıklar",
        items: [
          "Kuru Meyve",
          "Kuruyemiş",
          "Cips",
          "Çikolata",
          "Gofret",
          "Bisküvi",
          "Kraker",
          "Şekerleme",
          "Sakız",
          "Protein Bar",
          "Sağlıklı Atıştırmalıklar",
          "Unlu Mamüller",
          "Kek",
        ],
      },
      {
        name: "Petshop",
        items: [
          "Kedi Maması",
          "Kedi Kumu",
          "Köpek Maması",
          "Kedi Vitamini",
          "Köpek Tasması",
          "Kuş Ürünleri",
          "Akvaryum Ürünleri",
          "Kedi Box & Taşıma Çantaları",
          "Kedi ve Köpek Oyuncakları",
          "Kedi Yaş Mamaları",
          "Kedi Ödül Mamaları",
          "Köpek Ödül Mamaları",
          "Kısır Kedi Mamaları",
          "Kedi Şampuanı",
          "Su ve Mama Kapları",
          "Kuş Yemleri",
          "Kedi ve Köpek Yatakları",
          "Yavru Kedi Mamaları",
          "Akvaryum Balık Yemi",
          "Kedi Tuvaleti",
          "Kedi Fırça ve Tarağı",
        ],
      },
    ],
  },

  {
    name: "Kozmetik",
    icon: kozmetik,
    subcategories: [
      {
        name: "Makyaj",
        items: [
          "Göz Makyajı",
          "Ten Makyajı",
          "Dudak Makyajı",
          "Makyaj Seti",
          "Oje & Aseton",
          "Fondöten",
          "Ruj",
          "Dudak Kremi",
          "Maskara",
          "Eyeliner",
          "Göz Kalemi",
          "Kapatıcılar",
          "Allık",
          "Highlighter",
          "BB & CC Krem",
          "Kontür ve Paletler",
          "Bronzer",
          "Pudra",
          "Takma Tırnak",
          "Far Paleti",
        ],
      },
      {
        name: "Cilt Bakımı",
        items: [
          "Yüz Kremi",
          "Yüz Temizleme",
          "Yüz Maskesi",
          "Göz Bakımı",
          "Güneş Koruyucu",
          "Cilt Serumu",
          "El & Ayak Bakımı",
          "Tonikler",
          "Nemlendiriciler",
          "Yüz Maskeleri",
          "Peeling",
          "El Kremleri",
          "Vücut Losyonları",
          "Selülit Kremleri",
          "Makyaj Temizleyici",
          "Güneş Kremleri",
          "At Kılı Fırçalar",
          "Bronzlaştırıcılar",
          "Cilt Sıkılaştırıcılar",
          "Vücut Spreyleri",
        ],
      },
      {
        name: "Saç Bakımı",
        items: [
          "Şampuan",
          "Saç Şekillendirici",
          "Saç Serumu & Maskesi",
          "Saç Boyası",
          "Mor Şampuan",
          "Kuru Şampuan",
          "Saç Köpüğü",
          "Saç Kremi",
          "Saç Bakım Yağı",
          "Fön Suyu",
          "Saç Bakım Spreyi",
          "Renk Açıcı",
          "Geçici Saç Boyaları",
          "Saç Makası",
          "Tarak",
          "Saç Bantları",
          "Toka",
          "Saç Vitamini",
          "Saç Toniği",
          "Wax",
        ],
      },
      {
        name: "Kişisel Bakım",
        items: [
          "Duş Jelleri",
          "Banyo Sabunları",
          "Şampuan",
          "Pamuk",
          "Vücut Spreyleri",
          "Parfüm",
          "Deodorant",
          "Ağız Bakım Suyu",
          "Diş Fırçası",
          "Diş Macunu",
          "Diş İpi",
          "Şarjlı Diş Fırçaları",
          "Törpüler",
          "Kaş Makası",
          "Günlük Ped",
          "Measne Pedi",
          "Kese",
          "Banyo Lifi",
          "Diş Beyazlatıcı",
          "Gıda Takviyeleri",
        ],
      },
      {
        name: "Parfüm & Deodorant",
        items: [
          "Parfüm",
          "Parfüm Setleri",
          "Deodorant",
          "Vücut Spreyi",
          "Roll-On",
        ],
      },
      {
        name: "Saç Şekillendirici",
        items: ["Saç Köpüğü", "Saç Spreyi", "Jöle", "Wax"],
      },
      {
        name: "Makyaj Aksesuarları",
        items: [
          "Makyaj Fırçaları",
          "Makyaj Süngerleri",
          "Makyaj Çantaları",
          "Makyaj Aynaları",
          "Cımbız",
          "Kirpik Kıvırıcı",
          "Manikür & Pedikür Setleri",
        ],
      },
      {
        name: "Epilasyon & Tıraş",
        items: [
          "Tüy Dökücü",
          "Ağda",
          "Tıraş Bıçağı",
          "Epilatör",
          "Tıraş Köpüğü",
          "Ağda Bantları",
          "Tüy Dökücü Krem",
        ],
      },
      {
        name: "Genel Bakım",
        items: [
          "Cinsel Sağlık",
          "Hijyenik Ped",
          "Vücut Bakımı",
          "El ve Ayak Bakımı",
          "Duş Jeli ve Kremi",
          "Bakım Yağları",
          "Ayak Törpüleri",
          "Katı Sabun",
          "Sıvı Sabun",
          "Pamuk",
          "El Dezenfektanı",
        ],
      },
    ],
  },

  {
    name: "Ayakkabı & Çanta",
    icon: ayakkabi_canta,
    subcategories: [
      {
        name: "Kadın Ayakkabı",
        items: [
          "Spor Ayakkabı",
          "Topuklu Ayakkabı",
          "Günlük Ayakkabı",
          "Bot & Bootie",
          "Sandalet",
          "Terlik",
          "Sneaker",
          "Babet",
          "Loafer",
          "Anne Ayakkabısı",
          "Taşlı Sandalet",
          "Hastane Terlikleri",
          "Topuklu Terlik",
          "Topuklu Bot",
          "Çizme",
          "Kovboy Çizmesi",
          "Dolgu Topuk Ayakkabı",
          "Kar Botu",
          "Yağmur Botu",
          "Panduf",
        ],
      },
      {
        name: "Erkek Ayakkabı",
        items: [
          "Spor Ayakkabı",
          "Günlük Ayakkabı",
          "Klasik Ayakkabı",
          "Bot",
          "Sneaker",
          "Koşu Ayakkabısı",
          "Krampon",
          "Loafer",
          "Halı Saha Ayakkabısı",
          "Sandalet",
          "Bot",
          "Çizme",
          "Postal",
          "Basketbol Ayakkabısı",
          "Terlik",
          "Ev Terliği",
          "Panduf",
          "Deniz Ayakkabısı",
          "Süet Ayakkabı",
          "Yürüyüş Ayakkabısı",
        ],
      },
      {
        name: "Çocuk Ayakkabı",
        items: [
          "Saat",
          "Güneş Gözlüğü",
          "Cüzdan",
          "Kemer",
          "Şapka",
          "Bileklik",
          "Kravat",
          "Kolye",
          "Rozet",
          "Papyon",
        ],
      },
      {
        name: "Çocuk Çanta",
        items: [
          "Sırt Çantası",
          "Okul Çantası",
          "Çekçekli Çanta",
          "Beslenme Çantası",
          "Lisanslı Çantalar",
          "Bel Çantası",
          "Postacı Çanta",
        ],
      },
      {
        name: "Erkek Aksesuar",
        items: [
          "Saat",
          "Güneş Gözlüğü",
          "Cüzdan",
          "Kemer",
          "Şapka",
          "Bileklik",
          "Kravat",
          "Kolye",
          "Rozet",
          "Papyon",
        ],
      },
      {
        name: "Kadın Aksesuar",
        items: [
          "Saat",
          "Takı",
          "Şapka",
          "Güneş Gözlüğü",
          "Saç Aksesuarları",
          "Kemer",
          "Gümüş Kolye",
          "Hasır Bilezik",
        ],
      },
      {
        name: "Kadın Çanta",
        items: [
          "Omuz Çantası",
          "Sırt Çantası",
          "Cüzdan",
          "Spor Çantası",
          "Bel Çantası",
          "El Çantası",
          "Portföy",
          "Bez Çanta",
          "Kartlık",
          "Abiye Çanta",
          "Postacı Çantası",
          "Plaj Çantası",
          "Laptop Çantası",
          "Kapitone Çanta",
          "Evrak Çantası",
          "Kutu Çanta",
          "Makyaj Çantası",
          "Peluş Çanta",
          "Hasır Çanta",
          "Valiz & Bavul",
        ],
      },
      {
        name: "Erkek Çanta",
        items: [
          "Sırt Çantası",
          "Postacı Çantası",
          "Cüzdan & Kartlık",
          "Spor Çantası",
          "Laptop Çantası",
          "Bel Çantası",
          "Omuz Çantası",
          "Portföy Çanta",
          "Tıraş Çantası",
          "Olta Çantası",
          "Okul Çantası",
          "Valiz",
          "Outdoor Çanta",
          "El Çantası",
        ],
      },
      {
        name: "Lüks & Designer",
        items: ["Lüks Çanta", "Lüks Ayakkabı"],
      },
    ],
  },
  {
    name: "Elektronik",
    icon: elektronik,
    subcategories: [
      {
        name: "Küçük Ev Aletleri",
        items: [
          "Süpürge",
          "Robot Süpürge",
          "Dikey Süpürge",
          "Ütü",
          "Kahve Makinesi",
          "Çay Makinesi",
          "Blender Seti",
          "Tost Makinesi",
          "Doğrayıcı & Rondo",
          "Su Isıtıcı & Kettle",
          "Mikser & Mikser Seti",
          "Airfryer & Fritöz",
        ],
      },
      {
        name: "Giyilebilir Teknoloji",
        items: ["Akıllı Saat", "Akıllı Bileklik", "VR Gözlük"],
      },
      {
        name: "Telefon",
        items: [
          "Cep Telefonu",
          "Android Cep Telefonları",
          "İphone Cep Telefonu",
          "Telefon Kılıfları",
          "Şarj Cihazları",
          "Powerbank",
          "Araç İçi Telefon Tutucu",
          "İphone Kılıflar",
          "Kulaklıklar",
        ],
      },
      {
        name: "Foto & Kamera",
        items: [
          "Aksiyon Kamera",
          "Fotoğraf Makinesi",
          "Video Kamera",
          "Şipşak Fotoğraf Makinesi",
          "Dijital Fotoğraf Makinesi",
          "Kamera Lensleri",
          "Hafıza Kartı",
        ],
      },
      {
        name: "TV & Görüntü & Ses",
        items: [
          "Televizyon",
          "Smart TV",
          "QLED TV",
          "OLED TV",
          "Tv Kumandaları",
          "Soundbar",
          "Projeksiyon Cihazı",
          "Media Player",
          "Hoparlör",
          "Kulaklık",
          "Uydu Alıcısı",
          "Çanak Anten",
          "HDMI Kablo",
          "Akım Korumalı Prizler",
          "Kablo & Adaptör",
          "LNB",
          "TV Ekran Koruyucu",
          "TV Askı Aparatı",
          "Kablolu Hoparlör",
        ],
      },
      {
        name: "Beyaz Eşya",
        items: [
          "Buzdolabı",
          "Çamaşır Makinesi",
          "Bulaşık Makinesi",
          "Kurutma Makinesi",
          "Derin Dondurucu",
          "Ankastre Setler",
          "Kombi",
          "Mikrodalga Fırın",
          "Aspiratör",
          "Mini & Midi Fırın",
          "Ankastre Davlumbaz",
          "Ankastre Ocak",
        ],
      },
      {
        name: "Dijital Kod & Ürünler",
        items: [
          "Dijital Hediye Kartları",
          "E-pin & Cüzdan Kodları",
          "Ön Ödemeli Kartlar",
        ],
      },
      {
        name: "Bilgisayar & Tablet",
        items: [
          "Bilgisaylar",
          "Tablet",
          "Bilgisayar Bileşenleri",
          "Monitör",
          "Yazıcı & Tarayıcı",
          "Ağ & Modem",
          "Klavye",
          "Mouse",
          "Grafik Tablet",
          "SSD",
          "RAM",
          "Ekran Kartı",
          "Çocuk Çizim Tableti",
        ],
      },
      {
        name: "Kişisel Bakım ALetleri",
        items: [
          "Saç Düzleştirici",
          "Saç Maşası",
          "Saç Kurutma Makinesi",
          "Tıraş Makinesi",
          "Tartı",
          "Epilasyon Aletleri",
          "IPL Lazer Epilasyon",
        ],
      },
    ],
  },
  {
    name: "Spor & Outdoor",
    icon: spor_outdoor,
    subcategories: [
      {
        name: "Spor Üst Giyim",
        items: [
          "Spor Tişört",
          "Ceket & Yelek",
          "Yağmurluk",
          "Spor Sütyeni",
          "Sweatshirt",
          "Atlet",
          "Forma",
          "Spor Mont",
          "Spor Şapka",
        ],
      },
      {
        name: "Spor Alt Giyim",
        items: [
          "Eşofman Takımı",
          "Tayt",
          "Şort",
          "Termal Giyim",
          "Çorap",
          "Spor Pantolon",
          "Terlik",
          "Eşofman",
        ],
      },
      {
        name: "Spor Ayakkabı",
        items: [
          "Sneaker",
          "Koşu Ayakkabısı",
          "Halı Saha Ayakkabısı",
          "Basketbol Ayakkabısı",
          "Yürüyüş Ayakkabısı",
          "Outdoor Ayakkabı",
          "Tenis Ayakkabısı",
          "Voleybol Ayakkabısı",
          "Fitness Ayakkabısı",
          "Deniz Ayakkabısı",
          "Outdoor Ayakkabı",
          "Tenis Ayakkabısı",
          "Voleybol Ayakkabısı",
          "Fitness Ayakkabısı",
          "Deniz Ayakkabısı",
          "Outdoor Bot",
          "Terlik",
          "Sandalet",
          "Çizme",
          "Bot",
          "Kar Botu",
          "Kayak Ayakkabısı",
          "Snowboard Botu",
          "Havuz Terliği",
        ],
      },
      {
        name: "Evde Spor Aletleri",
        items: [
          "Elastik Bant",
          "El Yayı",
          "Mat",
          "Çalışma İstasyonları",
          "Atlama İpi",
          "Boks Eldiveni",
          "Dambıl Seti",
          "Eliptik Bisiklet",
          "Barfiks Barı",
          "Eldiven",
          "Kettlebell",
          "Kondisyon Bisikleti",
          "Yürüme Bandı",
          "Pilates Topu",
          "Kürek Çekme Aleti",
          "Boks Bandajı",
          "Crossfit",
        ],
      },
      {
        name: "Spor Malzemeleri",
        items: [
          "Deniz & Plaj",
          "Kaykay",
          "Paten",
          "Kamp Malzemeleri",
          "Dağcılık & Tırmanış",
          "Aksiyon Kamera",
          "Çadır Uyku Tulumu",
          "Su Sporu Malzemeleri",
          "Dalış Malzemeleri",
          "Balıkçılık Malzemeleri",
          "Tenis Malzemeleri",
          "Kayak ve Snowboard",
          "Okçuluk",
          "Çadır",
          "Havlu",
          "Suluk",
          "Matlar",
          "Bisiklet",
          "Termos",
          "Pilates Topları",
        ],
      },
      {
        name: "Bisiklet",
        items: [
          "Şehir Bisikleti",
          "Dağ Bisikleti",
          "Katlanabilir Bisikletler",
          "Yol Bisikletleri",
          "Çocuk Bisikletleri",
          "Elektrikli Bisikletler",
          "Bisikletçi Ekipmanları",
          "Bisiklet Gözlükleri",
          "Bisiklet Kaskları",
        ],
      },
      {
        name: "Fitness Kondisyon",
        items: [
          "Pilates Malzemeleri",
          "Fitness Aletleri",
          "Kondisyon Bisikleti",
          "Koşu Bandı",
          "Yoga Malzemeleri",
          "Dambıl Seti",
          "Ağırlık Plakaları",
          "Barfiks",
        ],
      },
      {
        name: "Sporcu Besinleri",
        items: [
          "Protein Tozu",
          "Amino Asit",
          "Karbonhidrat",
          "L-Karnitin(CLA)",
          "Güç ve Performans",
          "Gıda Takviyesi & Vitaminler",
          "Kreatin",
          "Protein Bar",
          "Shaker",
        ],
      },
      {
        name: "Top",
        items: ["Basketbol Topu", "Futbol Topu"],
      },
    ],
  },
  {
    name: "Kitap & Kırtasiye & Hobi",
    icon: kirtasiye,
    subcategories: [
      {
        name: "Parti Malzemeleri",
        items: [
          "Led Işık",
          "Düğün & Kına",
          "Yılbaşı Süsü",
          "Yılbaşı Ağacı",
          "Balon",
          "Parti Seti",
        ],
      },
      {
        name: "Hobi Malzemeleri",
        items: ["Örgü İpi", "Boncuk", "Kumaş", "Nakış Kiti", "Örgü Kiti"],
      },
      {
        name: "Müzik Aletleri",
        items: ["Pikap & Gramofon", "Gitar", "Plak", "Piyango", "Org", "Keman"],
      },
      {
        name: "Hediyelik Ürünler",
        items: [
          "Konsept Hediyelik",
          "Figür",
          "Hediye Kutusu",
          "Kar Küresi",
          "Paketleme Malzemesi",
        ],
      },
      {
        name: "Drone",
      },
      {
        name: "Uzaktan Kumandalı Araçlar",
      },
      {
        name: "Oyun Grupları",
        items: [
          "Puzzle",
          "Oyun Kartları",
          "Okey Takımı",
          "Satranç",
          "Maket",
          "Tavla",
        ],
      },
      {
        name: "Çakmak Ürünleri",
        items: ["Benzinli Çakmak", "Klasik Çakmak"],
      },
      {
        name: "Kırtasiye",
        items: [
          "Defter",
          "Ajanda",
          "Etiket",
          "Suluk & Matara",
          "Yazı Tahtası",
          "Pano",
          "Silgi",
          "Makas",
          "Yapıştırıcı",
        ],
      },
      {
        name: "Ofis",
        items: [
          "Fotokopi Kağıdı",
          "Pil & Şarj Cihazı",
          "Yazarkasa ve Terazi",
          "Hesap Makinesi",
          "Dosya & Klasör",
          "Zımba & Delgeç",
          "Para Sayma Makinesi",
          "Ciltleme Makinesi",
          "Ofis Sarf Tüketim",
        ],
      },
      {
        name: "Kalem",
        items: [
          "Keçeli Kalem",
          "Fosforlu Kalem",
          "Uçlu Kalem",
          "Tükenmez Kalem",
          "Kurşun Kalem",
          "Kalem Kutusu",
          "Kalem Ucu",
          "Tahta Kalemi",
          "Teknik Çizim Kalemi",
        ],
      },
      {
        name: "Boya & Sanatsal Malzemeler",
        items: [
          "Akrilik Boya",
          "Tuval & Şövalye",
          "Sanatsal Kağıt",
          "Kuru Boya Kalemi",
          "Fırça",
          "Kumaş Boyası",
          "Pastel Boya",
          "Sulu Boya",
          "Ahşap Boyası",
        ],
      },
      {
        name: "Eğitim",
        items: [
          "Sınav Hazırlık",
          "TYT & AYT",
          "KPSS",
          "LGS",
          "Ders ve Yardımcı Kitaplar",
          "Tarih",
          "Güncel-Genel Konular",
          "Sözlük & İmla Kılavuzu",
          "Tıp Kitabı",
          "Bilim & Teknik & Mühendislik",
          "Hukuk Kitabı",
        ],
      },
      {
        name: "E-Kitap Okuyucu",
      },
      {
        name: "Çocuk ve Ebeveyn Kitapları",
        items: [
          "Aktivite & Eğitici Kitaplar",
          "Çocuk Masal ve Öykü Kitabı",
          "Çocuk Bakımı & Ebeveynlik",
          "Boyama Kitapları",
          "Sesli Çocuk Kitapları",
        ],
      },
      {
        name: "Din ve Mitoloji",
      },
      {
        name: "Roman ve Edebiyat",
        items: [
          "Roman",
          "Dünya Edebiyatı",
          "Türk Edebiyatı",
          "Deneme & İnceleme",
          "Biyografi",
          "Şiir",
          "Anı & Günlük & Seyahatname",
        ],
      },
      {
        name: "Kişisel Gelişim",
        items: ["Bireysel Gelişim", "Psikoloji"],
      },
      {
        name: "Yabancı Dil Kitaplar",
        items: [
          "Yabancı Dil Eğitimi",
          "Yabancı Dil Roman",
          "Yabancı Dil Çocuk Kitapları",
        ],
      },
      {
        name: "Hobi,Sanat,Akademik",
      },
      {
        name: "Çizgi Roman,Dergi ve Gazete",
      },
      {
        name: "İş, Ekonomi & Pazarlama",
      },
    ],
  },
];

const CategoryDropdown = () => {
  const [activeCategory, setActiveCategory] = useState(null);

  return (
    <div className="CategoryDropdown">
      <div className="dropdown_container">
        <ul className="category-list">
          {data.map((category, index) => (
            <li
              key={index}
              className="category-item"
              onMouseEnter={() => setActiveCategory(category)}
              onMouseLeave={() => setActiveCategory(null)}
            >
              <div className="category_item_description">
                <img src={category.icon} alt="category.name" />
                {category.name}
              </div>
              <img src={right_icon} />
            </li>
          ))}
        </ul>

        {activeCategory && (
          <div
            className="subcategory-panel"
            onMouseEnter={() => setActiveCategory(activeCategory)}
            onMouseLeave={() => setActiveCategory(null)}
          >
            {activeCategory?.subcategories?.map((sub, i) => (
              <div key={i} className="subcategory-column">
                <div className="subcategory_row">
                  <span className="subcategory_column_name">{sub.name}</span>
                  <img src={right_icon} />
                </div>
                <ul>
                  {sub.items?.map((item, j) => (
                    <li key={j}>
                      <a className="subcategory_item">{item}</a>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default CategoryDropdown;
